apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: cicd
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: aaraoz/nodeapp:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: cicd
spec:
  selector:
    app: nodeapp
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodepapp
  namespace: cicd
  labels:
    name: nodeapp
  annotations:
    nginx.ingress.kubernetes.io/scheme: internet-facing
    nginx.ingress.kubernetes.io/target-type: ip
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: external-nginx
  rules:
  - host: mundose.geekeando.ar
    http:
      paths:
      - pathType: Prefix
        path: /node
        backend:
          service:
            name: nodeapp-service
            port: 
              number: 3000
